inherit_gem:
  datarockets-style:
    - config/ruby.yml

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Security/Open:
  Exclude:
    - 'lib/actions/ingredients_list/parse_ingredients.rb'
